# Generated by Django 3.0.5 on 2020-04-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('content_type', models.CharField(max_length=200)),
                ('enc_item_key', models.TextField()),
                ('auth_hash', models.CharField(max_length=200)),
                ('user_uuid', models.CharField(max_length=200)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_user_agent', models.TextField()),
            ],
        ),
    ]
